<?php

namespace Database\Seeders;

use App\Models\Inventory;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    public function run(): void
    {
        $images = [
            'white_suv' => 'demo/inventory/hero-suv-white.jpg',
            'blue_highlander' => 'demo/inventory/hero-highlander-blue.jpg',
            'road_suv' => 'demo/inventory/hero-suv-road.jpg',
            'red_sedan' => 'demo/inventory/hero-red-sedan.jpg',
            'red_sports' => 'demo/inventory/hero-sports-red.jpg',
            'gray_rav4' => 'demo/inventory/hero-rav4-gray.jpg',
            'dark_truck' => 'demo/inventory/hero-truck-dark.jpg',
            'silver_sequoia' => 'demo/inventory/hero-sequoia-silver.jpg',
        ];

        $vehicles = [
            [
                'status' => 'available',
                'is_featured' => true,
                'year' => 2021,
                'make' => 'Toyota',
                'model' => 'Sequoia',
                'trim' => 'Platinum',
                'price' => 45800,
                'doc_fee' => 367,
                'filing_fee' => 99,
                'tag_fee' => 27,
                'mileage' => 65210,
                'stock' => 'NMU-TY2101',
                'vin' => '5TDJY5G16MS210101',
                'engine' => '5.7L V8',
                'transmission' => '6-Speed Automatic',
                'drivetrain' => '4WD',
                'exterior' => 'Magnetic Gray',
                'interior' => 'Black Leather',
                'fuel' => 'Gasoline',
                'main_image' => $images['silver_sequoia'],
                'gallery' => [
                    $images['silver_sequoia'],
                    $images['white_suv'],
                    $images['blue_highlander'],
                    $images['road_suv'],
                ],
                'description' => 'Well-kept full-size SUV with strong road presence, premium seating, and a practical third row for family use.',
                'features' => ['Heated front seats', 'Sunroof', 'Navigation', 'Backup camera', 'Premium JBL audio'],
            ],
            [
                'status' => 'available',
                'is_featured' => true,
                'year' => 2020,
                'make' => 'Toyota',
                'model' => 'Land Cruiser',
                'trim' => 'Heritage Edition',
                'price' => 69800,
                'doc_fee' => 367,
                'filing_fee' => 99,
                'tag_fee' => 27,
                'mileage' => 48220,
                'stock' => 'NMU-TY2102',
                'vin' => 'JTMCY7AJ2L4210102',
                'engine' => '5.7L V8',
                'transmission' => '8-Speed Automatic',
                'drivetrain' => '4WD',
                'exterior' => 'Midnight Black',
                'interior' => 'Black Leather',
                'fuel' => 'Gasoline',
                'main_image' => $images['white_suv'],
                'gallery' => [
                    $images['white_suv'],
                    $images['road_suv'],
                    $images['silver_sequoia'],
                    $images['dark_truck'],
                ],
                'description' => 'Legendary Toyota SUV with premium comfort, V8 power, and serious off-road capability in a refined package.',
                'features' => ['Leather seats', '360 camera', 'Blind spot monitor', 'Cool box', 'Roof rack'],
            ],
            [
                'status' => 'available',
                'is_featured' => true,
                'year' => 2022,
                'make' => 'Toyota',
                'model' => 'Highlander',
                'trim' => 'XLE',
                'price' => 37900,
                'doc_fee' => 367,
                'filing_fee' => 99,
                'tag_fee' => 27,
                'mileage' => 28110,
                'stock' => 'NMU-TY2103',
                'vin' => '5TDGZRBH0NS210103',
                'engine' => '3.5L V6',
                'transmission' => '8-Speed Automatic',
                'drivetrain' => 'FWD',
                'exterior' => 'Blueprint',
                'interior' => 'Black SofTex',
                'fuel' => 'Gasoline',
                'main_image' => $images['blue_highlander'],
                'gallery' => [
                    $images['blue_highlander'],
                    $images['white_suv'],
                    $images['gray_rav4'],
                    $images['road_suv'],
                ],
                'description' => 'Clean midsize SUV with modern safety tech, strong resale appeal, and a comfortable cabin for daily use.',
                'features' => ['Apple CarPlay', 'Power liftgate', 'Heated seats', 'Blind spot monitor', 'Lane keep assist'],
            ],
            [
                'status' => 'available',
                'is_featured' => false,
                'year' => 2019,
                'make' => 'Toyota',
                'model' => '4Runner',
                'trim' => 'Limited',
                'price' => 41250,
                'doc_fee' => 367,
                'filing_fee' => 99,
                'tag_fee' => 27,
                'mileage' => 71440,
                'stock' => 'NMU-TY2104',
                'vin' => 'JTEBU5JR7K5210104',
                'engine' => '4.0L V6',
                'transmission' => '5-Speed Automatic',
                'drivetrain' => '4WD',
                'exterior' => 'Barcelona Red',
                'interior' => 'Black Leather',
                'fuel' => 'Gasoline',
                'main_image' => $images['road_suv'],
                'gallery' => [
                    $images['road_suv'],
                    $images['white_suv'],
                    $images['gray_rav4'],
                    $images['dark_truck'],
                ],
                'description' => 'Reliable body-on-frame SUV that balances rugged capability with comfort and classic Toyota dependability.',
                'features' => ['Sunroof', 'Leather interior', 'Tow package', 'Running boards', 'Premium audio'],
            ],
            [
                'status' => 'available',
                'is_featured' => false,
                'year' => 2023,
                'make' => 'Toyota',
                'model' => 'Camry',
                'trim' => 'XSE V6',
                'price' => 33600,
                'doc_fee' => 367,
                'filing_fee' => 99,
                'tag_fee' => 27,
                'mileage' => 12880,
                'stock' => 'NMU-TY2105',
                'vin' => '4T1KZ1AK7PU210105',
                'engine' => '3.5L V6',
                'transmission' => '8-Speed Automatic',
                'drivetrain' => 'FWD',
                'exterior' => 'Wind Chill Pearl',
                'interior' => 'Cockpit Red',
                'fuel' => 'Gasoline',
                'main_image' => $images['red_sedan'],
                'gallery' => [
                    $images['red_sedan'],
                    $images['red_sports'],
                    $images['blue_highlander'],
                    $images['gray_rav4'],
                ],
                'description' => 'Sporty sedan with sharp styling, V6 performance, and a comfortable tech-forward interior.',
                'features' => ['Red leather seats', 'Panoramic roof', 'Adaptive cruise control', 'Wireless charging', 'JBL speakers'],
            ],
            [
                'status' => 'available',
                'is_featured' => false,
                'year' => 2021,
                'make' => 'Toyota',
                'model' => 'RAV4',
                'trim' => 'XLE Premium',
                'price' => 29850,
                'doc_fee' => 367,
                'filing_fee' => 99,
                'tag_fee' => 27,
                'mileage' => 34125,
                'stock' => 'NMU-TY2106',
                'vin' => '2T3A1RFV8MW210106',
                'engine' => '2.5L I4',
                'transmission' => '8-Speed Automatic',
                'drivetrain' => 'AWD',
                'exterior' => 'Silver Sky',
                'interior' => 'Ash',
                'fuel' => 'Gasoline',
                'main_image' => $images['gray_rav4'],
                'gallery' => [
                    $images['gray_rav4'],
                    $images['blue_highlander'],
                    $images['white_suv'],
                    $images['road_suv'],
                ],
                'description' => 'Popular compact SUV with low running costs, sharp design, and practical everyday versatility.',
                'features' => ['Power liftgate', 'Blind spot monitor', 'Sunroof', 'Leatherette trim', 'Dual-zone climate'],
            ],
            [
                'status' => 'sold',
                'is_featured' => false,
                'year' => 2018,
                'make' => 'Toyota',
                'model' => 'Sequoia',
                'trim' => 'SR5',
                'price' => 0,
                'doc_fee' => 367,
                'filing_fee' => 99,
                'tag_fee' => 27,
                'mileage' => 89320,
                'stock' => 'NMU-TY2107',
                'vin' => '5TDZY5G18JS210107',
                'engine' => '5.7L V8',
                'transmission' => '6-Speed Automatic',
                'drivetrain' => 'RWD',
                'exterior' => 'Silver Sky',
                'interior' => 'Graphite',
                'fuel' => 'Gasoline',
                'main_image' => $images['silver_sequoia'],
                'gallery' => [
                    $images['silver_sequoia'],
                    $images['white_suv'],
                    $images['blue_highlander'],
                    $images['road_suv'],
                ],
                'description' => 'Previously sold family-size Toyota SUV with solid service history and roomy cabin layout.',
                'features' => ['Third-row seating', 'Backup camera', 'Tow package', 'Bluetooth', 'Power seats'],
            ],
            [
                'status' => 'sold',
                'is_featured' => false,
                'year' => 2020,
                'make' => 'Toyota',
                'model' => 'Avalon',
                'trim' => 'Limited',
                'price' => 0,
                'doc_fee' => 367,
                'filing_fee' => 99,
                'tag_fee' => 27,
                'mileage' => 40220,
                'stock' => 'NMU-TY2108',
                'vin' => '4T1BZ1FB7LU210108',
                'engine' => '3.5L V6',
                'transmission' => '8-Speed Automatic',
                'drivetrain' => 'FWD',
                'exterior' => 'Harbor Gray',
                'interior' => 'Beige Leather',
                'fuel' => 'Gasoline',
                'main_image' => $images['red_sports'],
                'gallery' => [
                    $images['red_sports'],
                    $images['red_sedan'],
                    $images['gray_rav4'],
                    $images['white_suv'],
                ],
                'description' => 'Elegant full-size sedan that offered smooth highway comfort, premium materials, and Toyota reliability.',
                'features' => ['Ventilated seats', 'Heated steering wheel', 'Navigation', 'Adaptive cruise', 'Premium audio'],
            ],
            [
                'status' => 'sold',
                'is_featured' => false,
                'year' => 2019,
                'make' => 'Toyota',
                'model' => 'Tacoma',
                'trim' => 'TRD Off-Road',
                'price' => 0,
                'doc_fee' => 367,
                'filing_fee' => 99,
                'tag_fee' => 27,
                'mileage' => 55780,
                'stock' => 'NMU-TY2109',
                'vin' => '3TMCZ5AN1KM210109',
                'engine' => '3.5L V6',
                'transmission' => '6-Speed Automatic',
                'drivetrain' => '4WD',
                'exterior' => 'Army Green',
                'interior' => 'Black Cloth',
                'fuel' => 'Gasoline',
                'main_image' => $images['dark_truck'],
                'gallery' => [
                    $images['dark_truck'],
                    $images['road_suv'],
                    $images['silver_sequoia'],
                    $images['gray_rav4'],
                ],
                'description' => 'Sold Toyota pickup with strong off-road trim, durable build quality, and solid resale appeal.',
                'features' => ['Locking rear differential', 'Crawl control', 'All-terrain tires', 'Touchscreen audio', 'Tow hitch'],
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Inventory::updateOrCreate(
                ['stock' => $vehicle['stock']],
                $vehicle
            );
        }
    }
}
